---
services:
  postgres:
    image: postgres:15.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pesapie
      POSTGRES_DB: pesapie_dev
      POSTGRES_PASSWORD: pazzwerdz
    container_name: pesapie-db
